### ISSUE TITLE
Database in pure Go

### ISSUE THREAD

**Issue by tredoe** [johnwilson/bytengine#3]
Hi! This is a really interesting project.

But it would be easier to deploy if were used togethere to any database in pure Go:
- [A low-level key/value database for Go](https://github.com/boltdb/bolt)
- [A high performance NoSQL like Redis powered by Go](http://ledisdb.com/)
- [tiedot - Your NoSQL database powered by Golang](https://github.com/HouzuoGuo/tiedot)

**Comment by johnwilson** [comment]
Thanks!

I haven't taken a closer look at any of those databases you're suggesting but if you have any experience using them then please do contribute by creating plugins:
* a tiedot plugin would implement [filesystem interface](https://github.com/johnwilson/bytengine/blob/master/filesystem.go)
* a ledisdb plugin would implement [statestore interface](https://github.com/johnwilson/bytengine/blob/master/statestore.go)

cheers.
